project:
  type: book
  title: "Skrub - Machine learning with dataframes (Book)"
  output-dir: ../_build/book

book:
  title: "Skrub like a pro - Book"
  author: "Riccardo Cappuzzo"
  page-navigation: true
  sidebar: false
  navbar:
    background: primary
    left:
      - text: "Home"
        href: ../index.html
      - text: "Book"
        href: index.html
      - text: "Slides"
        href: ../slides/index.html
      - text: "JupyterLite"
        href: ../jupyterlite/lab/
  chapters:
    - index.qmd
    - part: "Exploring and sanitizing data"
      chapters:
        - chapters/01_exploring_data.qmd
        - chapters/02_cleaning_data.qmd
    - part: "Transforming columns"
      chapters:
        - chapters/03_feat_eng_apply.qmd
        - chapters/04_selectors.qmd
    - part: "Feature Engineering with skrub"
      chapters:
        - chapters/05_table_vectorizer.qmd
        - chapters/06_tabular_pipeline.qmd
        - chapters/07_feature_eng_all.qmd
    - part: "Advanced pipelines"
      chapters:
        - chapters/08_data_ops.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
    code-fold: false
    code-tools: true

execute:
  freeze: auto
  keep-ipynb: true